### ISSUE TITLE
Plus de choix dans le positionnement du fond?

### ISSUE THREAD

**Issue by Eragonfr** [Doocode/Doosearch#3]
Je trouve dommage que mon fond de doosearch soit coupé sur les bords, je propose l'ajout d'options pour permettre de choisir si le fond doit être coupé, agrandi, zoomé ou autre

**Comment by Aero15** [comment]
Normalement, Doosearch remplit l'écran avec le fond, c'est étrange que ça bug. Tu es sur quel OS et sur quel navigateur web ? Pour ce qui est des options, je prend note pour la prochaine MAJ.

**Comment by Eragonfr** [comment]
Ce n'est pas un bug mais un ajoute de fonctionnalité, mon fond étant largement plus grand que mon écran de 15 pouces(certains de mes fonds sont en 4K... et mon écran ne sera jamais capable de les afficher)
